---
- name: single stream test harness
  hosts: senders[0]
  tasks:
    - ping:
    - name: generate random logfile name in /tmp
      set_fact:
        iperf_logfile: "/tmp/iperf_{{ lookup('password', '/dev/null chars=ascii_lowercase,digits length=12') }}.json"
    - name: start single stream test with JSON output
      shell: iperf3 -V -c "{{ groups['receivers'][0] }}" -J --logfile "{{ iperf_logfile }}"
    - name: fetch log data
      fetch:
        src: "{{ iperf_logfile }}"
        dest: "{{ playbook_dir }}"
      
